# Строгие настройки анализатора для Tonkatsu Box
# Максимальная типизация и лучшие практики

include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true        # Запрет неявных приведений типов
    strict-inference: true    # Требовать явные типы
    strict-raw-types: true    # Запрет raw generic типов

  errors:
    # Превратить warnings и infos в errors для консистентности с CI
    # CI использует --fatal-infos --fatal-warnings
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    dead_code: error
    unused_import: error
    unused_local_variable: error
    prefer_const_declarations: error
    unrelated_type_equality_checks: error

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    # Обязательная типизация
    always_declare_return_types: true
    always_specify_types: true
    avoid_dynamic_calls: true
    type_annotate_public_apis: true

    # Immutability
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # Null safety
    avoid_null_checks_in_equality_operators: true
    null_check_on_nullable_type_parameter: true
    null_closures: true

    # Стиль кода
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_void: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    hash_and_equals: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_key_in_widget_constructors: true
    use_rethrow_when_possible: true
    use_super_parameters: true
    valid_regexps: true

    # Документация
    public_member_api_docs: false  # Включить для библиотек: true

    # Именование
    camel_case_extensions: true
    camel_case_types: true
    constant_identifier_names: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    package_prefixed_library_names: true
