import 'package:flutter_test/flutter_test.dart';
import 'package:tonkatsu_box/shared/models/wishlist_tag.dart';

void main() {
  group('buildImportTag', () {
    test('returns <source>-<unix-ms> shape with parseable suffix', () {
      final String tag = buildImportTag('MyAnimeList');
      expect(tag, startsWith('MyAnimeList-'));

      final int? ms = int.tryParse(tag.substring('MyAnimeList-'.length));
      expect(ms, isNotNull);
      expect(ms, greaterThan(0));
    });

    test('two back-to-back calls produce distinct tags', () async {
      final String a = buildImportTag('Source');
      // Distinct timestamps require crossing a clock tick; await Future.delayed
      // with a 1ms delay is enough on every supported platform.
      await Future<void>.delayed(const Duration(milliseconds: 2));
      final String b = buildImportTag('Source');
      expect(a, isNot(b));
    });
  });

  group('parseWishlistTag', () {
    test('decodes <source>-<ms> into source and timestamp', () {
      final DateTime now = DateTime.now();
      final String tag = 'MyAnimeList-${now.millisecondsSinceEpoch}';

      final WishlistTagInfo info = parseWishlistTag(tag);
      expect(info.source, 'MyAnimeList');
      expect(info.timestamp, isNotNull);
      expect(info.isAutoGenerated, isTrue);
      expect(
        info.timestamp!.millisecondsSinceEpoch,
        now.millisecondsSinceEpoch,
      );
    });

    test('keeps multi-dash source names intact', () {
      final WishlistTagInfo info = parseWishlistTag('Source-name-1700000000000');
      expect(info.source, 'Source-name');
      expect(info.isAutoGenerated, isTrue);
    });

    test('manual tag without ms suffix stays as source-only', () {
      final WishlistTagInfo info = parseWishlistTag('handpicked');
      expect(info.source, 'handpicked');
      expect(info.timestamp, isNull);
      expect(info.isAutoGenerated, isFalse);
    });

    test('trailing dash is not treated as a suffix', () {
      final WishlistTagInfo info = parseWishlistTag('weird-');
      expect(info.source, 'weird-');
      expect(info.isAutoGenerated, isFalse);
    });

    test('non-numeric suffix is not treated as a timestamp', () {
      final WishlistTagInfo info = parseWishlistTag('Source-handpicked');
      expect(info.source, 'Source-handpicked');
      expect(info.isAutoGenerated, isFalse);
    });
  });
}
