// Wishlist tag helpers: filter type + auto-tag parsing.

/// Three-way filter used by the wishlist UI: show everything, show only
/// untagged items, or show items carrying a specific tag.
sealed class WishlistTagFilter {
  const WishlistTagFilter();

  /// No filtering — return every wishlist item.
  const factory WishlistTagFilter.all() = WishlistTagFilterAll;

  /// Only items with `tag IS NULL`.
  const factory WishlistTagFilter.untagged() = WishlistTagFilterUntagged;

  /// Only items carrying the given tag value.
  const factory WishlistTagFilter.named(String tag) = WishlistTagFilterNamed;
}

/// "Show everything" variant of [WishlistTagFilter].
final class WishlistTagFilterAll extends WishlistTagFilter {
  /// Creates a [WishlistTagFilterAll].
  const WishlistTagFilterAll();
}

/// "Only untagged" variant of [WishlistTagFilter].
final class WishlistTagFilterUntagged extends WishlistTagFilter {
  /// Creates a [WishlistTagFilterUntagged].
  const WishlistTagFilterUntagged();
}

/// "Specific tag" variant of [WishlistTagFilter].
final class WishlistTagFilterNamed extends WishlistTagFilter {
  /// Creates a [WishlistTagFilterNamed].
  const WishlistTagFilterNamed(this.tag);

  /// Tag value to match exactly.
  final String tag;
}

/// Parsed view of an auto-generated import tag (`%source%-<unix-ms>`).
class WishlistTagInfo {
  /// Creates a [WishlistTagInfo].
  const WishlistTagInfo({required this.source, this.timestamp});

  /// Human-readable source identifier ("MyAnimeList", "AniList") or, if the
  /// tag wasn't auto-generated, the raw tag itself.
  final String source;

  /// Generation timestamp parsed from the trailing millisecond suffix, or
  /// null for manually-typed tags that don't follow the auto-tag format.
  final DateTime? timestamp;

  /// `true` when the tag matched the `<source>-<unix-ms>` format and has a
  /// usable timestamp — UI can render it as "Source — date time".
  bool get isAutoGenerated => timestamp != null;
}

/// Builds an auto-generated tag for a single import run.
String buildImportTag(String source) =>
    '$source-${DateTime.now().millisecondsSinceEpoch}';

/// Parses an auto-generated tag back into source name + timestamp. Tags that
/// don't fit the pattern come back as [WishlistTagInfo] with a null timestamp
/// so callers can still display the raw value.
WishlistTagInfo parseWishlistTag(String tag) {
  final int sep = tag.lastIndexOf('-');
  if (sep <= 0 || sep == tag.length - 1) {
    return WishlistTagInfo(source: tag);
  }

  final String suffix = tag.substring(sep + 1);
  final int? ms = int.tryParse(suffix);
  if (ms == null || ms <= 0) {
    return WishlistTagInfo(source: tag);
  }

  return WishlistTagInfo(
    source: tag.substring(0, sep),
    timestamp: DateTime.fromMillisecondsSinceEpoch(ms),
  );
}
